name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      xvfb:
    strategy:
      matrix:
        go-version: ["1.17", "1.18", "1.19", "1.20"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install xsel
      run: sudo apt-get install xsel
    - name: Install xclip
      run: sudo apt-get install xclip
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -v .
